// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO3Cbq8DswJJZwUbfZ4vHqCYHN_vDDFhI',
    appId: '1:583256479568:web:2bc413b10934967a117e55',
    messagingSenderId: '583256479568',
    projectId: 'tugas-pmob1',
    authDomain: 'tugas-pmob1.firebaseapp.com',
    storageBucket: 'tugas-pmob1.appspot.com',
    measurementId: 'G-Y553M253VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZngYdFm7nKM7pP1-Kgsiq67gS4eXxF_k',
    appId: '1:583256479568:android:afdfd074ff2e69a9117e55',
    messagingSenderId: '583256479568',
    projectId: 'tugas-pmob1',
    storageBucket: 'tugas-pmob1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2LdZjbtmp5Ul8sGCVJ_MvnuwcO22Ap8Y',
    appId: '1:583256479568:ios:1595c8e312058d71117e55',
    messagingSenderId: '583256479568',
    projectId: 'tugas-pmob1',
    storageBucket: 'tugas-pmob1.appspot.com',
    iosBundleId: 'com.example.mycalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2LdZjbtmp5Ul8sGCVJ_MvnuwcO22Ap8Y',
    appId: '1:583256479568:ios:1595c8e312058d71117e55',
    messagingSenderId: '583256479568',
    projectId: 'tugas-pmob1',
    storageBucket: 'tugas-pmob1.appspot.com',
    iosBundleId: 'com.example.mycalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO3Cbq8DswJJZwUbfZ4vHqCYHN_vDDFhI',
    appId: '1:583256479568:web:cdd3192a0d1ee916117e55',
    messagingSenderId: '583256479568',
    projectId: 'tugas-pmob1',
    authDomain: 'tugas-pmob1.firebaseapp.com',
    storageBucket: 'tugas-pmob1.appspot.com',
    measurementId: 'G-FJ16JBEGE2',
  );
}
